name: Build and push tags

run-name: Build and push tags

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  increment-server-tag:
    runs-on: ubuntu-latest

    outputs:
      latest_server_tag: ${{ steps.tag.outputs.next_server_tag }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - id: tag
        name: Resolve latest tag and increment
        run: |
          latest_server_tag=$(git tag --list 'server-v*' --sort=-v:refname | head -n 1)

          if [ -z "$latest_server_tag" ]; then
            next_server_tag="server-v1.0.0"
          else
            version="${latest_server_tag#server-v}"
            major=$(echo "$version" | cut -d. -f1)
            minor=$(echo "$version" | cut -d. -f2)
            patch=$(echo "$version" | cut -d. -f3)

            patch=$((patch + 1))
            next_server_tag="server-v$major.$minor.$patch"
          fi

          git tag $next_server_tag
          git push origin $next_server_tag
          echo "next_server_tag=$next_server_tag" >> "$GITHUB_OUTPUT"

  increment-client-tag:
    runs-on: ubuntu-latest

    outputs:
      latest_client_tag: ${{ steps.tag.outputs.next_client_tag }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - id: tag
        name: Resolve latest tag and increment
        run: |
          latest_client_tag=$(git tag --list 'client-v*' --sort=-v:refname | head -n 1)

          if [ -z "$latest_client_tag" ]; then
            next_client_tag="client-v1.0.0"
          else
            version="${latest_client_tag#client-v}"
            major=$(echo "$version" | cut -d. -f1)
            minor=$(echo "$version" | cut -d. -f2)
            patch=$(echo "$version" | cut -d. -f3)

            patch=$((patch + 1))
            next_client_tag="client-v$major.$minor.$patch"
          fi

          git tag $next_client_tag
          git push origin $next_client_tag
          echo "next_client_tag=$next_client_tag" >> "$GITHUB_OUTPUT"

  build-server:
    runs-on: ubuntu-latest
    needs: increment-server-tag
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: '22.20'
      - run: npm ci
      - run: npm run build

  build-client:
    runs-on: ubuntu-latest
    needs: increment-client-tag
    defaults:
      run:
        working-directory: ./client

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: '22.20'
      - run: npm ci
      - run: npm run build

  build-server-image:
    runs-on: ubuntu-latest
    outputs: 
      server_image_tag: ${{ steps.tag.outputs.image_tag }}

    needs: 
      - build-server
      - increment-server-tag

    defaults:
      run:
        working-directory: ./server
    
    steps:
      - name: Clone the repository
        uses: actions/checkout@v6
      - id: tag
        name: Build and tag Docker image
        run: |
          git_server_tag=${{ needs.increment-server-tag.outputs.latest_server_tag }}
          image_tag=${{ github_server_tag }}

          docker build -t chats:$image_tag .
          echo "image_tag=$image_tag" >> "$GITHUB_OUTPUT"
      
  push-server-image-to-ecr:
    runs-on: ubuntu-latest
    needs:
      - build-image-server
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: arn:aws:iam::461201847742:role/github-actions-ecr-push
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Push server Docker image to ECR
        run: |
          image_tag=${{ needs.build-image-server.outputs.server_image_tag }}
          docker push ${{ secrets.ECR_REPO }}:${{ image_tag }}